### ISSUE TITLE
Files: Txfr fails when source URL is from github release.

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#134]
It appears that transferring from a github release URL is failing.
Test used: sourceURI=https://github.com/scblack321/test-zip-app/archive/refs/tags/0.1.tar.gz

Error in files worker log (in DEV environment):

> 2023-12-15 19:35:19.705 TRACE [pool-9055-thread-1] e.u.t.t.f.l.s.ChildTaskTransferService:859 - FILES_TXFR_CHILD_SYNCH_BEGIN Tenant: dev User: testuser2 ID: 95,207 Tag: 8e80af0e-0433-4e24-a246-585fd9e33488 UUID: a950c48a-2f06-4c3d-b42a-22241cbaa64f SourceSystem: github.com SourcePath: scblack321/test-zip-app/archive/refs/tags/0.1.tar.gz DestSystem: tapisv3-smoketest-exec-fork DestPath: workdir/jobs/eafc31c3-851b-43e5-88a4-0773ecbb67a3-007
> 2023-12-15 19:35:19.712 ERROR [ChildPool:193-11340] e.u.t.t.f.l.s.ChildTaskTransferService:636 - Expected URL scheme 'http' or 'https' but no colon was found
> java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
>     at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
>     at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService.doTransfer(ChildTaskTransferService.java:631)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService.lambda$runPipeline$4(ChildTaskTransferService.java:141)
>     at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:56)
>     at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:76)
>     at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
>     at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
>     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
>     at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
>     at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
>     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
>     at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
>     at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:173)
>     at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815)
>     at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
>     at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:76)
>     at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
>     at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
>     at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
>     at reactor.core.publisher.FluxSubscribeOnValue$ScheduledScalar.run(FluxSubscribeOnValue.java:180)
>     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
>     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
>     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>     at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
>     at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)
>     at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
>     at okhttp3.Request$Builder.url(Request.kt:184)
>     at edu.utexas.tacc.tapis.files.lib.clients.HTTPClient.getStream(HTTPClient.java:92)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService.performSynchFileTransfer(ChildTaskTransferService.java:863)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService.stepTwo(ChildTaskTransferService.java:414)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService$1.call(ChildTaskTransferService.java:616)
>     at edu.utexas.tacc.tapis.files.lib.services.ChildTaskTransferService$1.call(ChildTaskTransferService.java:612)
>     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
>     ... 3 common frames omitted
> 2023-12-15 19:35:19.714 INFO  [ChildPool:193-11340] reactor.rabbitmq.Receiver:228 - Cancelling consumer amq.ctag-mF7t7LCb5wQj23eZgAtVfA consuming from control.0120b136-a4fd-4d3b-ba7d-63d1a7f43f73
> 2023-12-15 19:35:19.794 ERROR [ChildPool:193-11340] e.u.t.t.f.l.s.ChildTaskTransferService:530 - FILES_TXFR_SVC_ERR10 ERROR. Child task failed!  Child task: TransferTaskChild[id=95207, tag=null, parentTaskId=90564, taskId=37678, externalTaskId=, retries=1, tenantId='dev', username='testuser2', sourceURI='https://github.com/scblack321/test-zip-app/archive/refs/tags/0.1.tar.gz', destinationURI='tapis://tapisv3-smoketest-exec-fork/workdir/jobs/eafc31c3-851b-43e5-88a4-0773ecbb67a3-007', uuid=a950c48a-2f06-4c3d-b42a-22241cbaa64f, totalBytes=0, bytesTransferred=0, status='IN_PROGRESS', created=2023-12-15T19:35:19.458964Z, startTime=2023-12-15T19:35:19.640454Z, endTime=null]
>

**Comment by scblack321** [comment]
Performing internet searches using phrase
> java error "Expected URL scheme"


Gives hints that this may be related to okhttp or possibly react code.

**Comment by scblack321** [comment]
Duplicate of #138. Already fixed.
