### ISSUE TITLE
Files: Unable to list files for AWS S3 Bucket

### ISSUE THREAD

**Issue by scblack321** [tapis-project/tapis-files#46]
Reported by John West while using tapipy via jupyter notebook running against Files Version: 1.2.0-b2590229 in DEV environment.
Error:
```
ServerDownError                           Traceback (most recent call last)
/var/folders/qv/b0klq0xs4fzdgl0y09dqv5wm0000gp/T/ipykernel_21618/3095656914.py in <module>
----> 1 t.files.listFiles(systemId="tapisjwest.docs.test", path="/")
ServerDownError: message: Unable to execute HTTP request: URI does not specify a valid host name: https:/%2Ftapisbucket.s3.amazonaws.com/%2F
```
System definition:
```
"#To register the S3 bucket with Tapis\n",
    "# the description of an S3 bucket\n",
    "s3_bucket = {\n",
    "  \"id\":\"tapisjwest.docs.test\",\n",
    "  \"description\":\"Tapis Docs Test Bucket\",\n",
    "  \"host\":\"tapisbucket.s3.us-east-1.amazonaws.com\",\n",
    "  \"systemType\":\"S3\",\n",
    "  \"defaultAuthnMethod\":\"ACCESS_KEY\",\n",
    "  \"bucketName\":\"tapisbucket\",\n",
    "  \"rootDir\":\"/\",\n",
    "  \"canExec\": False,\n",
    "}\n",
    "\n",
    "# create the system in Tapis\n",
    "t.systems.createSystem(**s3_bucket)"
```
Register creds:
```
"#userName is tacc user name\n",
    "t.systems.createUserCredential(systemId='tapisjwest.docs.test', \n",
    "                               userName='john', \n",
    "                               accessKey='***', \n",
    "                               accessSecret='***')\n"
```
List files:
```
"source": [
    "t.files.listFiles(systemId=\"tapisjwest.docs.test\", path=\"/\")"
```

**Comment by scblack321** [comment]
Reproduced error. Created S3 account using elj_4321.
Create bucket bucket named tapisdemotest2, object test1.txt.
Object URL: https://tapisdemotest2.s3.amazonaws.com/test1.txt
Created IAM user tapisdemo2 for programmatic access. Update cred with access key.
Attempted to list files:

```
2022-06-24 22:52:56.762 ERROR [grizzly-http-server-99] e.u.t.t.s.p.TapisExceptionMapper:29 - TapisExceptionMapper : 
software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: URI does not specify a valid host name: https:/%2Ftapisdemotest2.s3.amazonaws.com/%2F
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:199)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:66)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:4147)
	at edu.utexas.tacc.tapis.files.lib.clients.S3DataClient.doesExist(S3DataClient.java:470)
	at edu.utexas.tacc.tapis.files.lib.clients.S3DataClient.ls(S3DataClient.java:186)
	at edu.utexas.tacc.tapis.files.lib.services.FileOpsService.ls(FileOpsService.java:169)
	at edu.utexas.tacc.tapis.files.lib.services.FileOpsService.ls(FileOpsService.java:137)
	at edu.utexas.tacc.tapis.files.api.resources.OperationsApiResource.listFiles(OperationsApiResource.java:135)

```
